### ISSUE TITLE
The plugin does not work on IOS, leaving an empty component

### ISSUE THREAD

**Issue by arsanjea** [infinitered/ignite-maps#18]
- Issue:

After creating a brand you ignite app the ignite-maps does not work, displaying an empty component:
![nocomponent](https://user-images.githubusercontent.com/9323128/30672823-c416d018-9e3c-11e7-8f1a-2876baceb82f.gif)

- Steps to reproduce:
```
ignite new ignitemaps
cd ignitemaps/
ignite add maps
react-native run-ios
```
- Versions:
ignite 2.0.0
npm 5.4.2
react-native-cli 2.0.1
Xcode 8.3.3
macOS Sierra 10.12.6

- Git repo:
https://github.com/arsanjea/ignitemaps

![setupenvironment](https://user-images.githubusercontent.com/9323128/30672657-c5bc7a5e-9e3b-11e7-97a3-706eb2b61dbe.gif)

**Comment by GantMan** [comment]
Thanks for the catch!   I'll ring the alarm bells locally.  Any idea what's up?

**Comment by GantMan** [comment]
Also, we need to write a test that would have caught this.

**Comment by arsanjea** [comment]
I remember having the same problem a few months ago while using the npm
module in a different app. I don't recall how i solved it but I'll try to
dig it up.

**Comment by robinheinze** [comment]
I think we just need to upgrade the version of `react-native-maps` to 0.15+ (see https://github.com/airbnb/react-native-maps/issues/1193) since we recently bumped the boilerplate to RN 0.47.2. I'll try to get that in this morning!
