### ISSUE TITLE
painlessly

### ISSUE THREAD

**Issue by JohnnyTwoShoes** [infinitered/ignite-maps#21]
lol. painlessly!!!! 1 day wasted installing it. another to get it to run. still not working on 3rd day. pizzaApp doesn't run properly. and now im getting message:  ignite-ir-boilerplate is not available on npm.

**Comment by GantMan** [comment]
You seem quite beset with problems.

**Comment by skellock** [comment]
@JohnnyTwoShoes this is the `maps` repo. Please file an issue over on [infinitered/ignite-ir-boilerplate](https://github.com/infinitered/ignite-ir-boilerplate) and don't forget to list some details such as versions you're using.

We have a command called `ignite doctor` that can help.  

The most common problems I've seen is older version of the stack.  (like an old `ignite-cli`, old `yarn`, old `npm`, and even an old `node`).  There's even some strangeness around certain versions of `yarn` with certain versions of `node`.  

It's certainly not fun.

Don't forget manners too.  They go along way with both Open Source projects and life in general.
