### ISSUE TITLE
[Maybe?] Mapview broken in Android?

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite-maps#3]
Per https://github.com/infinitered/ignite/issues/570, map view may be broken in Android. This needs to be confirmed and more info added here. This is a placeholder for now.

**Comment by skellock** [comment]
For this issue, they needed to add their API key to `AndroidManifest.xml`.

Now having said that, there are other issues, but I'm doing PRs for them now.

**Comment by jamonholmgren** [comment]
Issue #8 would probably be useful to fix the issue https://github.com/infinitered/ignite/issues/570.

**Comment by jshumakerpruitt** [comment]
Just wanted to add that the app still crashed immediately for me after adding my api key.  The solution in this issue worked for me https://github.com/airbnb/react-native-maps/issues/1101

**Comment by skellock** [comment]
@jshumakerpruitt Sweet thx man.

I'll get another build out in the morning.  It includes this (#6) and a few other fixes.

**Comment by jshumakerpruitt** [comment]
Awesome, @skellock.  Your fix looks like a much cleaner way to ensure the proper version of play-services.

**Comment by skellock** [comment]
Just pushed the build out now.  `0.1.2` has this in place.  🌮
